### ISSUE TITLE
Two Bugs: markers persisting & typed letters

### ISSUE THREAD

**Issue by chrisgrieser** [tadashi-aikawa/obsidian-quick-jump-plugin#1] opened 2022-02-26 14:26 UTC
Thanks for yet another wonderful plugin!

Here are two bugs I found while testing:
1. Using the "Quick jump" a second time before you have opened a link causes the plugin to break, the markers never disappear again until you restart Obsidian
2. when the cursor is inside the document, pressing the letter for the jump will also type the letter in the editor 

---
Good news btw, the plugin also works in source mode, not only live preview.

**Comment by tadashi-aikawa** [comment] 2022-02-26 16:36
Hi, @chrisgrieser :) Thank you as always!

> Using the "Quick jump" a second time before you have opened a link causes the plugin to break, the markers never disappear again until you restart Obsidian

I have fixed it 👍 

> when the cursor is inside the document, pressing the letter for the jump will also type the letter in the editor

I couldn't reproduce it. Could you tell me more details?

**Comment by chrisgrieser** [comment] 2022-02-26 16:48
> I have fixed it 👍

great, thanks! 😊 

> I couldn't reproduce it. Could you tell me more details?

here, take a look:

https://user-images.githubusercontent.com/73286100/155851561-511fc04d-e71d-4389-b910-c1195565a660.mov

**Comment by tadashi-aikawa** [comment] 2022-02-26 16:53
Thanks!

I could reproduce it when I disable vim mode 👍

**Comment by tadashi-aikawa** [comment] 2022-02-26 17:04
Fixed in [v0.3.2](https://github.com/tadashi-aikawa/obsidian-quick-jump-plugin/releases/tag/0.3.2) 🚀

**Comment by chrisgrieser** [comment] 2022-02-26 17:07
you are so fast. thanks! 🤩

**Closed as completed** 2022-02-26 23:28 UTC
Labels: bug
